### ISSUE TITLE
Need to add in population data from some facilities that have extremely low pop numbers 

### ISSUE THREAD

**Issue by nmmarquez** [uclalawcovid19behindbars/facility_data#18]
Turner Residential Substance Abuse Treatment Prison in Georgia
Neuse Correctional Institution Prison in North Carolina

**Comment by erika-tyagi** [comment]
FYI: I made the `Population.Feb20` values for these two facilities NA yesterday, so rates are missing on the website instead of wildly high. 

Based on the [population status file](https://github.com/uclalawcovid19behindbars/Population/blob/main/initial/20.11.19_Pop_Status.xlsx), it seems like records requests from GA and NC were denied, so I figured might as well leave them blank while we figured out another way to get Feb 20 pop data for them.

**Comment by nmmarquez** [comment]
Im marking this as closed for now since facilities with NA are all over the place and we dont need to highlight these two specifically
